services:
  influxdb:
    image: influxdb:2.9.1
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: always
    networks:
      - monitoramento
    volumes:
      - ./diretorios/influxdb_data:/var/lib/influxdb2
      - ./diretorios/influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=lcade
      - DOCKER_INFLUXDB_INIT_PASSWORD=lcade@1234
      - DOCKER_INFLUXDB_INIT_ORG=LCADE
      - DOCKER_INFLUXDB_INIT_BUCKET=Monitoramento
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=7eWkP2R9xT4vLzQmJnYb8uCsK1wFaGhEjNdXyZpAqUr5tVwPx3oMiLvK9cDsBfGt

  telegraf:
    image: telegraf:1.31-alpine
    container_name: telegraf
    restart: always
    pid: "host" 
    volumes:
      - ./diretorios/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
    environment:
      - HOST_MOUNT_PREFIX=/hostfs
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
    networks:
      - monitoramento
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitoramento
    environment:
      - GF_SECURITY_ADMIN_USER=lcade
      - GF_SECURITY_ADMIN_PASSWORD=lcade@1234
      - GF_PLUGINS_AUTO_UPDATE=false
    volumes:
      - ./diretorios/grafana_data:/var/lib/grafana
      - ./diretorios/grafana-provisioning:/etc/grafana/provisioning/
    depends_on:
      - influxdb

networks:
  monitoramento:
    driver: bridge
