global:
  scrape_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'ping_google'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'download_google'
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: [http_2xx] 
    static_configs:
      - targets:
        - https://drive.google.com/uc?export=download&id=1rc9m6Z1TJwDcrFoYkk9CWKIA1tBn_bRT
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox:9115'
  
  - job_name: 'download_git'
    scrape_interval: 120s
    metrics_path: /probe
    params:
      module: [http_2xx] 
    static_configs:
      - targets:
        - https://drive.google.com/uc?export=download&id=1rc9m6Z1TJwDcrFoYkk9CWKIA1tBn_bRT
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox:9115'